<p><a href="<?php echo $this->url(array('controller' => 'index', 'action'=>'add')) ?>">Add new album</a></p>
<table border="1">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th></th>
    </tr>
    <?php foreach ($this->albums as $album) : ?>
    <tr>
        <td><?php echo $this->escape($album->title); ?></td>
        <td><?php echo $this->escape($album->artist); ?></td>
        <td>
            <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'edit', 'id' => $album->id)) ?>">Edit</a>
            <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'delete', 'id' => $album->id)) ?>">Delete</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
